### PR TITLE
add requirements.txt

### PR DESCRIPTION
**Pull request by shejain-hub**
Adding the requirements.txt file with this change - shelly

### CODE REVIEW

**Review by Cris-Fortes — CHANGES_REQUESTED** [review]
I'm afraid the file is empty. Did you save it locally before pushing it to GitHub?

**Review by Cris-Fortes — APPROVED** [review]
Looks good now!

**Comment by Cris-Fortes** [comment]
All good now with requirements document. Confirming the merge with the base (main).

**Comment by shejain-hub** [comment]
Deleting branch feature-add-requirements

**Pull request merged**
